// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJj5mJ1yO4uMaOom9h1m6NdjCAyWHcmeo',
    appId: '1:1073438904048:web:427aaaded72b4573e2bc35',
    messagingSenderId: '1073438904048',
    projectId: 'danny-instagram',
    authDomain: 'danny-instagram.firebaseapp.com',
    storageBucket: 'danny-instagram.appspot.com',
    measurementId: 'G-J2V5JH6WBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNf_V9oskLeGuhKtAOqbAkGTPvR3XSXAE',
    appId: '1:1073438904048:android:7e9ce96bab7cf8a6e2bc35',
    messagingSenderId: '1073438904048',
    projectId: 'danny-instagram',
    storageBucket: 'danny-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTTP9bHUf7-SK9-39Xe8ThFmJE9XhZZGE',
    appId: '1:1073438904048:ios:3a9e0b64414cd990e2bc35',
    messagingSenderId: '1073438904048',
    projectId: 'danny-instagram',
    storageBucket: 'danny-instagram.appspot.com',
    iosClientId: '1073438904048-gutgau1r1ls2nbgaj8qu341b3qqq59kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tentacles',
  );
}
